### ISSUE TITLE
Readings precision

### ISSUE THREAD

**Issue by DamianBroj** [wichers/esphome-comfoair#14]
What is the level of precision for values coming from CA? I see on some HA screens that it produces decimals, while in my case there's no decimals in readings. Is that something that is configurable?

**Comment by DamianBroj** [comment]
Based on discussions with other developer - max temp readings precision is 0.5°C (calculation of CA output is to be divided by 2 and deducted with 20). In current commit all sensors are set to decimal precision = 0. PR from @jjhuff is increasing precision which makes this issue resolved once implemented

**Comment by wichers** [comment]
Precision is based on your client side configuration, no changes necessary
in esp code. Although it should support 0.5 precision, I haven't heard of a
unit that does.

Op zo 6 feb. 2022 22:45 schreef DamianBroj ***@***.***>:
