### ISSUE TITLE
Upgrade : New mode focus and no current temperature

### ISSUE THREAD

**Issue by verstrepeng** [wichers/esphome-comfoair#17]
I just did an upgrade today and saw a new mode called focus, what is this mode ?
Attribute current_temperature also stays 0 (might have been the case before, didn't pay attention).

**Comment by wichers** [comment]
This commit was for private use, maybe I should not be pushing this to the
main branch, I used "focus" as I needed a function button to handle this
mode. In this mode (at least in my situation) the comfoair will be blowing
more in than out, I personally use this for our fireplace. I still need to
check if I can influence the amount of air being blown in and out. Mine is
set at full speed blowing in and set at the lowest speed blowing out.

To be continued..

**Comment by verstrepeng** [comment]
How can I remove the focus setting, as that one is not interesting for me...
Further, great job mate !

**Comment by wichers** [comment]
focus has been removed
