### ISSUE TITLE
getting error status

### ISSUE THREAD

**Issue by FreeKillerLP** [wichers/esphome-comfoair#21]
Hi, im getting a "getting error", when I try to get the values via log. I'm using wemos d1 Mini and the RB-RS232/GPI0-Shield board from Joyit as an adapter. My system: CA350 Luxe

![image](https://user-images.githubusercontent.com/68876429/226173818-b8aca5bd-15c8-4623-8d5a-69246088962b.jpeg)![image](https://user-images.githubusercontent.com/68876429/226173819-8a708aa6-2e00-48d2-afb2-0a877612773c.jpeg)

**Comment by wichers** [comment]
I see you have tx connected to tx, it should be tx to rx.

Op zo 19 mrt. 2023 13:03 schreef FreeKillerLP ***@***.***>:
