### ISSUE TITLE
Getting error while installing/compiling

### ISSUE THREAD

**Issue by waldek12345** [wichers/esphome-comfoair#25]
![377880418_6568373893244795_3398433015577800489_n](https://github.com/wichers/esphome-comfoair/assets/143165472/6f0d391f-80a4-4fe3-8dd1-bbc7788ca538)
![377946511_989053135704328_2352061312072579725_n](https://github.com/wichers/esphome-comfoair/assets/143165472/fbf51819-075a-4821-9ffc-3e449963c67a)

**Comment by wichers** [comment]
fixed in latest revision
