### ISSUE TITLE
[Question] Compability with StorkAir G91-350

### ISSUE THREAD

**Issue by KM192** [wichers/esphome-comfoair#3]
I have StorkAir G91-350 from 2009 year:
- is it compatible with this version
- how to connect esp (e.g. D1 Wemos version) with 350 interface ?

**Comment by wichers** [comment]
I was unable to find anything about the 'magic'? DB9 connector on this unit. The electrical schematic does show an A and B connected to pin 8 & 9 of the DB9 connector. For me the question is what this A & B is exposed to. From the high-res pcb picture I was unable to draw any conclusions.. At the very least we know the Philips P80C552EFA supports UART. If your adventurous and have a multimeter you could check if pin 24 & pin 25 (easy to find, next to the marked pin 26) of the Philips PLCC chip are directly or indirectly (especially check the two transistors and the 10k resistors near A & B) connected to A & B port.

![mceclip0](https://user-images.githubusercontent.com/578199/94191721-3e3a6380-feae-11ea-9462-c57fe1678505.png)

**Comment by pki791** [comment]
Hi.
A & B are the communiaction pins for RS485. The protocoll seems slightly different, seems it is like here https://matsab.de/de/heimautomatisierung/comfoair

I have done a test and seems it is willing to work. Log below. Is anyone willing to help and add this protocol too?

I have build a small converter TTL to RS485 with MAX485 and NE555, not complicated, auto RX/TX switching.



SEND
07 F0 00 85 00 32 07 0F

GOT
07 F3
07 F0 00 84 0A 00 12 00 30 4E 31 86 BE 01 00 41 07 0F
07 F0 00 84 0A 00 12 00 30 4E 31 86 BE 01 00 41 07 0F
07 F0 00 84 0A 00 12 00 30 4E 31 86 BE 01 00 41 07 0F
07 F0 00 84 0A 00 12 00 30 4E 31 86 BE 01 00 41 07 0F
07 F0 00 84 0A 00 12 00 30 4E 31 86 BE 01 00 41 07 0F

**Comment by pki791** [comment]
Interface i used to connect ESP8266 to RS485
![Zrzut ekranu z 2020-12-27 15-26-12](https://user-images.githubusercontent.com/59803213/103172997-13b6c880-4858-11eb-936d-0ab2569d703b.png)

**Comment by KM192** [comment]
Hi - I opened my CA 350 and it has RS232 port on the board:
![IMG_20210206_180037](https://user-images.githubusercontent.com/37086659/107151222-b71ff080-6961-11eb-87bb-1b1c8aea8898.jpg)
Do you think and RS232 <> USB Conector to ESP32 with ESPHome shoud work in this case ?

**Comment by wichers** [comment]
Closing this issue as the [protocol](https://matsab.de/images/comfoair/Protokoll_CA500_Avignon.pdf) is completely different. This requires a new implementation.
