### ISSUE TITLE
Standalone Comfoair-Esphome

### ISSUE THREAD

**Issue by bassguitarist** [wichers/esphome-comfoair#36]
Hi Wichers.
This is not an issue, but a "feature request"...

Thanks for your work on the Esphome-Comfoair interface. I'm using it since two months replacing the previous configuration with a RPi and a venv in Python <-> connected to Home Assistant.
A friend of mine would like to use the power of your solution but he's not running Home Assistant (nor other platforms). Would it be possible to run a "standalone" version of your solution, interacting throug http-api, just selecting the fan speed?

Thanks for your help

**Comment by wichers** [comment]
Definitely. You need to do a manual esphome [installation](https://esphome.io/guides/installing_esphome). Of course you need to remove the "api:" section from the  yaml, as that enabled HA communication. Have a look [here](https://esphome.io/web-api/index.html) for changing fan speed using the web-api.
