### ISSUE TITLE
[Request] Temperature precision 

### ISSUE THREAD

**Issue by geelenbert** [wichers/esphome-comfoair#5]
Temperatures are now updated in full degrees. But the precision of the device is 0.5 degrees. 
I'm not sure where I need to adjust this setting.

**Comment by wichers** [comment]
All sensors are updated and calculated with correct floating point (0.5) precision. Rounding takes place in the user interface, although stated, my WHR950 does not support 0.5 precision at all. If your unit supports 0.5 precision you should see your sensors being updated accordingly. If you're using the simple thermostat you could change the step_size to 0.5 for the target temperature, that should do it.
